general {
  lock_cmd = ~/.local/bin/btr-system-lock
  before_sleep_cmd = loginctl lock-session
  after_sleep_cmd = hyprctl dispatch 'hl.dsp.dpms({ action = "enable" })'
  inhibit_sleep = 3
}

listener {
  timeout = 300
  on-timeout = loginctl lock-session
}

listener {
  timeout = 330
  on-timeout = hyprctl dispatch 'hl.dsp.dpms({ action = "disable" })'
  on-resume = hyprctl dispatch 'hl.dsp.dpms({ action = "enable" })'
}
