#!/usr/bin/env bash

echo "Installing Vundler"
if test -e ~/.vim/bundle/Vundle.vim; then
  pushd ~/.vim/bundle/Vundle.vim
    git pull
  popd
else
  pushd ~/.vim/bundle
    git clone https://github.com/gmarik/Vundle.vim.git
  popd
fi
